import { DocsPage, DocsBody } from "fumadocs-ui/page"

export default function TermsOfServicePage() {
  const toc = [
    { title: "Acceptance of Terms", url: "#acceptance", depth: 2 },
    { title: "User Portal Conduct", url: "#conduct", depth: 2 },
    { title: "Educator Responsibilities", url: "#educators", depth: 2 },
    { title: "Financial Transactions", url: "#finance", depth: 2 },
    { title: "Account Termination", url: "#termination", depth: 2 },
    { title: "Limitation of Liability", url: "#liability", depth: 2 },
  ]

  return (
    <DocsPage toc={toc}>
      <DocsBody>
        <div className="space-y-3">
          <h1 className="text-3xl font-extrabold tracking-tight text-foreground sm:text-4xl" id="overview">
            Terms of Service
          </h1>
          <p className="text-base text-muted-foreground leading-relaxed">
            Last Updated: July 8, 2026. These Terms of Service regulate access and use of the VidyaSchool digital portal, mobile applications, and student information systems.
          </p>
        </div>

        <section className="space-y-4 pt-6">
          <h2 className="text-xl font-bold text-foreground" id="acceptance">1. Acceptance of Terms</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            By registering an account, completing onboarding profiles, or using any portal services, you agree to be bound by these Terms of Service. If you disagree with any segment of these clauses, portal access must be discontinued.
          </p>
        </section>

        <section className="space-y-4 pt-6">
          <h2 className="text-xl font-bold text-foreground" id="conduct">2. User Portal Conduct</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Users must provide accurate, truthful details during onboarding (such as legitimate admission keys and phone numbers). Sharing login sessions or social credentials is prohibited. Harassment or inappropriate language on community chat boards will trigger immediate disciplinary reviews.
          </p>
        </section>

        <section className="space-y-4 pt-6">
          <h2 className="text-xl font-bold text-foreground" id="educators">3. Educator Responsibilities</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Teachers and librarians must maintain academic integrity when publishing marks and entering classroom registers. All Educator accounts require administrative screening and approval. Unauthorized modifications of grading schemas will lead to account suspension.
          </p>
        </section>

        <section className="space-y-4 pt-6">
          <h2 className="text-xl font-bold text-foreground" id="finance">4. Financial Transactions</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Tuition fee processing utilizes third-party gateways (Razorpay). Users must ensure UPI credentials or bank credit details are secure. VidyaSchool is not liable for transactions failed at banking networks. Official digital receipts generated by the accountant module are final evidence of settlement.
          </p>
        </section>

        <section className="space-y-4 pt-6">
          <h2 className="text-xl font-bold text-foreground" id="termination">5. Account Termination</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            We reserve the right to suspend or terminate accounts that breach portal rules, violate academic guidelines, or post false information. Suspended users will be redirected to the unauthorized error dashboard.
          </p>
        </section>

        <section className="space-y-4 pt-6">
          <h2 className="text-xl font-bold text-foreground" id="liability">6. Limitation of Liability</h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            The VidyaSchool portal is provided on an "as-is" and "as-available" baseline. We do not guarantee uninterrupted system connection during maintenance cycles. We are not liable for transport delays or technical outages impacting online class submissions.
          </p>
        </section>
      </DocsBody>
    </DocsPage>
  )
}
